//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrarConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requirement()
        {
            this.Courses = new HashSet<Course>();
        }
    
        public int RequirementID { get; set; }
        public int HrsPerWeek { get; set; }
        public int InstructHr { get; set; }
        public int LabHr { get; set; }
        public int LibHr { get; set; }
        public bool Gaming { get; set; }
        public bool Program { get; set; }
        public bool Cad { get; set; }
        public bool Multi { get; set; }
        public Nullable<int> ClassHr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Courses { get; set; }
    }
}
