//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrarConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resource()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int ResourceID { get; set; }
        public bool Instruct { get; set; }
        public bool Lab { get; set; }
        public bool Classroom { get; set; }
        public bool PodWithProj { get; set; }
        public bool Smartboard { get; set; }
        public bool Gaming { get; set; }
        public bool Program { get; set; }
        public bool Cad { get; set; }
        public bool Multi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
