//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrarConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSchedule
    {
        public int StudentID { get; set; }
        public string RoomID { get; set; }
        public System.DateTime StartTime { get; set; }
        public int primaryKey { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual Student Student { get; set; }
    }
}
