//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrarConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentMajor
    {
        public Nullable<int> StudentID { get; set; }
        public string MajorID { get; set; }
        public int primaryKey { get; set; }
    
        public virtual Major Major { get; set; }
        public virtual Student Student { get; set; }
    }
}
