//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrarConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudentMajors = new HashSet<StudentMajor>();
            this.StudentSchedules = new HashSet<StudentSchedule>();
            this.UserInfoes = new HashSet<UserInfo>();
        }
    
        public int StudentID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string MIntial { get; set; }
        public int AddressID { get; set; }
        public int ContactID { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Contact Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentMajor> StudentMajors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentSchedule> StudentSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
    }
}
